### ISSUE TITLE
sourcemap-codec@1.4.8 package obsolète

### ISSUE THREAD

**Issue by jasiukiewicztymon** [doxa-tech/rencontredejeunesse#49]
Durant le `npm i` j'ai eu le warn d'un package obsolète. Je ne la change pas pour l'instant au vue des possibles problèmes avec la màj.

Si jamais il s'agit de la `sourcemap-codec@1.4.8` ➡️ `@jridgewell/sourcemap-codec`.

**Comment by khcr** [comment]
Merci, je vais mettre à jour !
